import type { Metadata } from "next";
import { Mogra, PT_Sans, Sekuya } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const mogra = Mogra({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-mogra",
});

const ptSans = PT_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-pt-sans",
});

const sekuya = Sekuya({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-sekuya",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${mogra.variable} ${ptSans.variable} ${sekuya.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
